function(fixCompilerType projName)
    if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
        xmake_add_to_property(${projName} COMPILE_FLAGS "/W0")
        xmake_add_to_list_property(${projName} COMPILE_DEFINITIONS "_CRT_SECURE_NO_DEPRECATE")
    elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
        xmake_add_to_property(${projName} COMPILE_FLAGS "-w")
    else()
        message(FATAL_ERROR "Unsupported compiler: ${CMAKE_C_COMPILER_ID}")
    endif()
endfunction(fixCompilerType)
